version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  website_backend:
    build:
      context: ../website_backend
    env_file:
      - ../website_backend/.env
    container_name: website_backend
    restart: unless-stopped
    depends_on:
      - mongo
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
    environment:
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DB: website_backend
    ports:
      - "5000:5000"
    volumes:
      - ../website_backend/app:/app/app
      - ../website_backend/uploads:/app/uploads


  mongo_express:
    image: mongo-express:1.0.2-20
    container_name: mongo_express
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "8081:8081"

volumes:
  mongo_data:

  website_frontend:
    build:
      context: ../website_frontend
    container_name: website_frontend
    restart: unless-stopped
    depends_on:
      - website_backend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://website_backend:5000
