version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  website_backend:
    build:
      context: ../website_backend
    env_file:
      - ../website_backend/.env
    container_name: website_backend
    restart: unless-stopped
    depends_on:
      - mongo
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
    environment:
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DB: website_backend
    ports:
      - "5000:5000"
    volumes:
      - ../website_backend/app:/app/app
      - ../website_backend/uploads:/app/uploads

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  telegram_service:
    build:
      context: ../telegram_service
    env_file:
      - ../telegram_service/.env
    container_name: telegram_service
    restart: unless-stopped
    depends_on:
      - website_backend
      - redis
    expose:
      - "8080"
    ports:
      - "8080:8080"

  website_frontend:
    build:
      context: ../website_frontend
    container_name: website_frontend
    restart: unless-stopped
    depends_on:
      - website_backend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://website_backend:5000
      - REACT_APP_API_URL=http://website_backend:5000

  reverse_proxy:
    image: caddy:2
    container_name: reverse_proxy
    restart: unless-stopped
    depends_on:
      - telegram_service
    ports:
      - "80:80"
      - "443:443"
    environment:
      AUTH_TELEGRAM_DOMAIN: ${AUTH_TELEGRAM_DOMAIN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      
  vacancy_collector:
    build:
      context: ../vacancy_collector
    container_name: vacancy_collector
    restart: unless-stopped
    depends_on:
      - redis

    env_file:
      - ../vacancy_collector/.env

    volumes:
      - ../vacancy_collector/sessions:/app/sessions

    environment:
      TG_SESSION: /app/sessions/vacancy_userbot

    stdin_open: true
    tty: true

  ai_worker:
    build:
      context: ../ai_worker
    container_name: ai_worker
    restart: unless-stopped
    depends_on:
      - redis
      - mongo
      - telegram_service
    env_file:
      - ../ai_worker/.env
    volumes:
      - ../website_backend/uploads:/app/uploads

volumes:
  mongo_data:
  caddy_data:
  caddy_config:
